<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.ccd.boot</groupId>
    <artifactId>ccd-spring-boot-aggregator</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>CUSTOM_STARTER/ccd-data-jpa-spring-boot-starter</module>
        <module>CUSTOM_STARTER/ccd-spring-boot</module>
        <module>CUSTOM_STARTER/ccd-spring-boot-starter</module>
        <module>CUSTOM_STARTER/ccd-spring-boot-starter-autoconfigure</module>
        <module>CUSTOM_STARTER/ccd-system-spring-boot-starter</module>
        <module>MODULE/ccd-data-jpa-spring-boot</module>
        <module>MODULE/ccd-system-spring-boot</module>
        <module>PLATFORM/ccd-spring-boot-dependencies</module>
    </modules>
</project>
