# 覆蓋預設設定，若設定重複則以 active profile 為主
# 1.if want override default 解開需要的複寫或是透過第2、3步驟找到其預設
# 2.按下 alt + / 或輸入關鍵字後按下 alt + / 則會跳出相關可設定的自動完成項目
# 3.若點擊其上一步自動完成項目，會跳到其 XXXXproperties.java 
####################################################
################ 以下 該專案自訂 ########################
####################################################
# 正式環境上一定要設定 -DBASEDIR=內容 or by docker env
# ref ccd/config/custom/system/ccd-default-system.yml 之 BASEDIR

####################################################
########## 第三方 spring boot starter ################
####################################################

####################################################
############ 以下 ccd custom starter ################
####################################################
# 1.if want override default custom starter 解開需要的複寫
# 2.輸入關鍵字. 後按下 alt + / 則會跳出相關可設定的自動完成項目
# 3.若點擊其上一步自動完成項目，會跳到其 XXXXproperties.java 
# 已知前墜 ccd.system

ccd:
  system:
    #id: client project 應該複寫
    #dir:  client project 應該複寫，由於 spring boot yml 無法用語法將變數自動轉大寫所以需要額外設定大寫目錄變數)
    basedir: ${BASEDIR:../CONFIG}
    path:
      config: ${ccd.system.basedir}/${ccd.system.dir}/config # option
      data: ${ccd.system.basedir}/${ccd.system.dir}/data # 永久存放
      temp: ${ccd.system.basedir}/${ccd.system.dir}/tmp # 暫存、需有對應清除機制
      log: ${ccd.system.basedir}/${ccd.system.dir}/log

####################################################
################ 以下 spring boot 內建 ################
####################################################