<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.ccd.twse</groupId>
		<artifactId>ccd-twse-parent</artifactId>
		<version>25.0.1-SNAPSHOT</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>

	<artifactId>ccd-system-spring-boot</artifactId>
	<name>ccd-system-spring-boot</name>
	<description>system自動配置設定 + 核心實作依賴</description>

	<properties>
	</properties>

	<dependencies>

        <!-- 1. 為了引用跨 spring boot 自訂定義 class -->
        <dependency><groupId>com.ccd</groupId><artifactId>ccd-spring-boot</artifactId></dependency> <!-- use CcdPrefixConfigurationProperties-->

        <!-- 2. spring boot data jpa 原本自動配置核心(裡面已涵蓋慣用依賴) -->

        <!-- 3. 自訂 data jpa core : data jpa 核心實作擴充邏輯(若有的話) -->


		<!-- optional 系列 -->
		<dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-configuration-processor</artifactId><optional>true</optional></dependency>
        <!-- 參考 spring boot data jpa github gradle 寫法 : 不然會缺少必要的 org.springframework.boot.autoconfigure 之 class 問題 -->
        <!-- ref https://github.com/spring-projects/spring-boot/blob/main/module/spring-boot-data-jpa/build.gradle -->
        <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-autoconfigure</artifactId><optional>true</optional></dependency>

	</dependencies>

</project>
